import registry from "./registry.ts";

export type OpenAPIOptions = {
  title?: string;
  version?: string;
  description?: string;
  outputPath?: string;
};

export function generateOpenAPI(
  options: OpenAPIOptions = {},
  registryToUse = registry,
) {
  const spec: any = {
    openapi: "3.1.0",
    info: {
      title: options.title || "Generated API",
      version: options.version || "1.0.0",
      description:
        options.description ||
        "API documentation generated by @di-framework/di-framework-http.",
    },
    paths: {},
    components: {
      schemas: {},
    },
  };

  const targets = registryToUse.getTargets();

  for (const target of targets) {
    // Look for endpoints on the target (static properties)
    for (const key of Object.getOwnPropertyNames(target)) {
      const property = target[key];
      if (property && property.isEndpoint) {
        const path = property.path || "/unknown";
        const method = property.method || "get";

        if (!spec.paths[path]) {
          spec.paths[path] = {};
        }

        spec.paths[path][method] = {
          summary: property.metadata?.summary || key,
          description: property.metadata?.description,
          operationId: `${target.name}.${key}`,
          requestBody: property.metadata?.requestBody,
          responses: property.metadata?.responses || {
            "200": {
              description: "OK",
            },
          },
        };
      }
    }
  }

  return spec;
}
